### ISSUE TITLE
AssertionError:  1

### ISSUE THREAD

**Issue by abhigenie92** [mjacar/pytorch-trpo#14]
```
2017-07-06 16:52:04,878] Making new env: CartPole-v1
Traceback (most recent call last):
  File "examples/cartpole_example.py", line 28, in <module>
    main()
  File "examples/cartpole_example.py", line 22, in main
    r = evaluate_policy(env, policy, 10000, 1.0, 100)
  File "utils/evaluation_utils.py", line 23, in evaluate_policy
    r += evaluate_episode(env, policy, maximum_episode_length=maximum_episode_length, discount_factor=discount_factor)
  File "utils/evaluation_utils.py", line 34, in evaluate_episode
    observation, immediate_reward, finished, info = env.step(action)
  File "env_wrappers/cartpole_wrapper.py", line 58, in step
    _, reward, done, info = self.env.step(action)
  File "/Users/abhishek/Packages/gym/gym/core.py", line 99, in step
    return self._step(action)
  File "/Users/abhishek/Packages/gym/gym/envs/classic_control/cartpole.py", line 57, in _step
    assert self.action_space.contains(action), "%r (%s) invalid"%(action, type(action))
AssertionError:
 1
```
The action return is Torch variable instead of int.

**Comment by mjacar** [comment]
This should be resolved now.
