### ISSUE TITLE
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

### ISSUE THREAD

**Issue by loadder** [mjacar/pytorch-trpo#16]
```
Traceback (most recent call last):
  File "example.py", line 25, in <module>
    main()
  File "example.py", line 18, in main   
   policy, diagnostics = agent.step()
  File "/home/xuchengming/pytorch-trpo/trpo_agent.py", line 326, in step
    self.observations, self.discounted_rewards, self.actions, self.action_dists, self.entropy = self.sample_trajectories()
  File "/home/xuchengming/pytorch-trpo/trpo_agent.py", line 187, in sample_trajectories
    observation = self.env.reset()
  File "/home/xuchengming/pytorch-trpo/env_wrappers/cartpole_wrapper.py", line 52, in reset
    return self.get_screen()
  File "/home/xuchengming/pytorch-trpo/env_wrappers/cartpole_wrapper.py", line 28, in get_screen
    screen = self.env.render(mode='rgb_array').transpose(
  File "/usr/local/lib/python3.5/dist-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/cartpole.py", line 115, in _render
    from gym.envs.classic_control import rendering
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/__init__.py", line 1884, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/__init__.py", line 1833, in get_default_display
    return pyglet.canvas.get_display()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/usr/local/lib/python3.5/dist-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None" 
```

**Comment by mjacar** [comment]
1. This repo is meant for python 2.7, not python 3.5 (though I don't think that's related to your issue).
2. How are you running it? I think I've seen that issue before when trying to render gym environments over ssh. I believe this to be the relevant issue: https://github.com/openai/gym/issues/735

**Comment by loadder** [comment]
@mjacar I personally revise the code into py3.5 style and run it on ubuntu server 16.04 over ssh and a jumpiest, I'll try the method you mentioned. Thanks!
