### ISSUE TITLE
no iteritems attribute in TRPOAgent ?

### ISSUE THREAD

**Issue by AjayTalati** [mjacar/pytorch-trpo#2]
Hi, thanks a lot for post this implementation of TRPO!

I tried to run the example, but I got the following error?

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/PythonProjects/pytorch-trpo-1-master$ python example.py
[2017-06-04 00:00:03,567] Making new env: CartPole-v1
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    main()
  File "example.py", line 11, in main
    agent = TRPOAgent(env, policy_model, value_function_model)
  File "/home/ajay/PythonProjects/pytorch-trpo-1-master/trpo_agent.py", line 116, in __init__
    for k, v in self.policy_model.state_dict().iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
```

**Comment by AjayTalati** [comment]
Oh I guess this is a Python 2 vs Python 3 thing. 

I got the repo working for Python 3, but I seem to get a lot of `nan`s. 

I was just wondering if this is inherent with using finite-difference approximations, or maybe there's some other problem? 

Thanks a lot for any feedback you can offer :+1: 

```
Evaluation avg reward = 460.460000 
KL_Old_New: 0.008619575761258602
Entropy: 0.5731614232063293
EV_Before: 0.975948058945988
EV_After: 0.9895277467420742
Evaluation avg reward = 494.080000 
KL_Old_New: 0.003692292608320713
Entropy: 0.5786159634590149
EV_Before: -0.08049038167348765
EV_After: nan
Evaluation avg reward = 494.800000 
KL_Old_New: 0.0
Entropy: 0.5660303235054016
EV_Before: nan
EV_After: nan
```

**Comment by tigerneil** [comment]
@mjacar I am confused on why nan for `ev_before` and `ev_after` after several steps.

**Comment by AjayTalati** [comment]
@tigerneil numerical instability?

**Comment by mjacar** [comment]
I was planning on working on this repo today anyway. I'll take a look at this as well. It's not something I've come across myself.
